### ISSUE TITLE
Pi camera does not work

### ISSUE THREAD

**Issue by mpous** [just4give/bird-watcher-fin#4]
The expected behaviour would be that the camera is detected.

However I get this error:

```
26.04.21 15:37:31 (+0200)  camera  /usr/local/lib/python3.5/dist-packages/aiortc/rtcdtlstransport.py:12: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
26.04.21 15:37:31 (+0200)  camera    from cryptography.hazmat.backends import default_backend
26.04.21 15:37:32 (+0200)  camera  Video device is not ready
26.04.21 15:37:32 (+0200)  camera  Trying to load bcm2835-v4l2 driver...
26.04.21 15:37:41 (+0200) Service exited 'camera sha256:083d866bf7c9b44a3e0285a2262aa804053f0845a02585ad52d673966e267529'
```

I'm using Raspberry Pi 3 with 32 bit balenaOS.

**Comment by mpous** [comment]
It works properly on webcam via USB.

**Comment by just4give** [comment]
@mpous does it work on Fin with Pi Cam ? I have not tested it with Pi3 but works on Fin for me.

**Comment by mpous** [comment]
@just4give now i was testing on pi3, later i will test with the fin :) Thanks!

**Comment by just4give** [comment]
Not sure but would you mind checking your configuration ? This is what I have. 

<img width="1377" alt="Screen Shot 2021-04-26 at 10 07 54 AM" src="https://user-images.githubusercontent.com/9275193/116096475-54dcaf00-a677-11eb-991c-1120d4cd2323.png">
